<?php

namespace App\Http\Requests\RaidHelper;

use Illuminate\Support\Collection;

class EventWebhookRequest extends RaidHelperWebhookRequest
{
    protected function webhookRules(): Collection
    {
        return collect($this->rules())
            ->keys()
            ->filter(fn ($key) => ! str_contains($key, '.') && ! str_contains($key, '*'))
            ->mapWithKeys(fn ($key) => [$key => []]);
    }

    /** @return array<string, array<int, string>> */
    public function rules(): array
    {
        return [
            // Required core fields
            'id' => ['required', 'string'],
            'serverId' => ['nullable', 'string'],
            'leaderId' => ['required', 'string'],
            'leaderName' => ['required', 'string'],
            'channelId' => ['required', 'string'],
            'title' => ['required', 'string'],
            'description' => ['nullable', 'string'],
            'startTime' => ['required', 'integer', 'before:endTime', 'after_or_equal:closingTime'],
            'endTime' => ['required', 'integer', 'after:startTime'],
            'closingTime' => ['nullable', 'integer', 'before_or_equal:startTime'],
            'closeTime' => ['nullable', 'integer'],
            'lastUpdated' => ['required', 'integer'],
            'color' => ['required', 'string'],

            // Optional top-level fields
            'channelName' => ['nullable', 'string'],
            'channelType' => ['nullable', 'string'],
            'templateId' => ['nullable', 'string'],
            'templateEmoteId' => ['nullable', 'string'],
            'date' => ['nullable', 'string'],
            'time' => ['nullable', 'string'],
            'softresId' => ['nullable', 'string'],
            'imageUrl' => ['nullable', 'string'],
            'signUpCount' => ['nullable', 'integer'],
            'scheduledId' => ['nullable', 'string'],
            'displayTitle' => ['nullable', 'string'],
            'announcements' => ['nullable', 'array'],

            // signUps
            'signUps' => ['nullable', 'array'],
            'signUps.*.id' => ['nullable', 'integer'],
            'signUps.*.name' => ['nullable', 'string'],
            'signUps.*.userId' => ['nullable', 'string'],
            'signUps.*.entryTime' => ['nullable', 'integer'],
            'signUps.*.status' => ['nullable', 'string'],
            'signUps.*.position' => ['nullable', 'integer'],
            'signUps.*.className' => ['nullable', 'string'],
            'signUps.*.classEmoteId' => ['nullable', 'string'],
            'signUps.*.specName' => ['nullable', 'string'],
            'signUps.*.specEmoteId' => ['nullable', 'string'],
            'signUps.*.roleName' => ['nullable', 'string'],
            'signUps.*.roleEmoteId' => ['nullable', 'string'],
            'signUps.*.cClassName' => ['nullable', 'string'],
            'signUps.*.cSpecName' => ['nullable', 'string'],
            'signUps.*.cRoleName' => ['nullable', 'string'],

            // classes
            'classes' => ['nullable', 'array'],
            'classes.*.name' => ['nullable', 'string'],
            'classes.*.emoteId' => ['nullable', 'string'],
            'classes.*.type' => ['nullable', 'string'],
            'classes.*.limit' => ['nullable', 'integer'],
            'classes.*.specs' => ['nullable', 'array'],
            'classes.*.specs.*.name' => ['nullable', 'string'],
            'classes.*.specs.*.emoteId' => ['nullable', 'string'],
            'classes.*.specs.*.roleName' => ['nullable', 'string'],
            'classes.*.specs.*.roleEmoteId' => ['nullable', 'string'],

            // roles
            'roles' => ['nullable', 'array'],
            'roles.*.name' => ['nullable', 'string'],
            'roles.*.limit' => ['nullable', 'integer'],
            'roles.*.emoteId' => ['nullable', 'string'],

            // advancedSettings
            'advancedSettings' => ['nullable', 'array'],
            'advancedSettings.duration' => ['nullable', 'integer', 'min:0'],
            'advancedSettings.deadline' => ['nullable', 'integer', 'min:0'],
            'advancedSettings.limit' => ['nullable', 'integer', 'min:0'],
            'advancedSettings.lockAtLimit' => ['nullable', 'boolean'],
            'advancedSettings.limitPerUser' => ['nullable', 'integer', 'min:0'],
            'advancedSettings.specsPerSignup' => ['nullable', 'integer', 'min:0'],
            'advancedSettings.showExtraSpecs' => ['nullable', 'boolean'],
            'advancedSettings.lowerLimit' => ['nullable', 'integer', 'min:0'],
            'advancedSettings.allowDuplicate' => ['nullable', 'boolean'],
            'advancedSettings.horizontalMode' => ['nullable', 'boolean'],
            'advancedSettings.benchOverflow' => ['nullable', 'boolean'],
            'advancedSettings.queueBench' => ['nullable', 'boolean'],
            'advancedSettings.vacuum' => ['nullable', 'boolean'],
            'advancedSettings.pinMessage' => ['nullable', 'boolean'],
            'advancedSettings.deletion' => ['nullable', 'string'],
            'advancedSettings.mentionMode' => ['nullable', 'boolean'],
            'advancedSettings.preserveOrder' => ['nullable', 'string'],
            'advancedSettings.applyUnregister' => ['nullable', 'boolean'],
            'advancedSettings.applySpecreset' => ['nullable', 'string'],
            'advancedSettings.specSaving' => ['nullable', 'boolean'],
            'advancedSettings.fontStyle' => ['nullable', 'integer', 'min:0'],
            'advancedSettings.altNames' => ['nullable', 'boolean'],
            'advancedSettings.defaultsPreReq' => ['nullable', 'boolean'],
            'advancedSettings.showOnOverview' => ['nullable', 'boolean'],
            'advancedSettings.mentionLeader' => ['nullable', 'boolean'],
            'advancedSettings.attendance' => ['nullable', 'string'],
            'advancedSettings.showTitle' => ['nullable', 'boolean'],
            'advancedSettings.showInfo' => ['nullable', 'boolean'],
            'advancedSettings.showLeader' => ['nullable', 'boolean'],
            'advancedSettings.showCounter' => ['nullable', 'boolean'],
            'advancedSettings.showRoles' => ['nullable', 'boolean'],
            'advancedSettings.showContent' => ['nullable', 'boolean'],
            'advancedSettings.showClasses' => ['nullable', 'boolean'],
            'advancedSettings.showEmotes' => ['nullable', 'boolean'],
            'advancedSettings.showNumbering' => ['nullable', 'boolean'],
            'advancedSettings.showAllowed' => ['nullable', 'boolean'],
            'advancedSettings.showFooter' => ['nullable', 'boolean'],
            'advancedSettings.infoVariant' => ['nullable', 'string'],
            'advancedSettings.dateVariant' => ['nullable', 'string'],
            'advancedSettings.format12h' => ['nullable', 'string'],
            'advancedSettings.showCountdown' => ['nullable', 'boolean'],
            'advancedSettings.disableArchiving' => ['nullable', 'boolean'],
            'advancedSettings.disableReason' => ['nullable', 'boolean'],
            'advancedSettings.boldAll' => ['nullable', 'boolean'],
            'advancedSettings.benchEmote' => ['nullable', 'string'],
            'advancedSettings.lateEmote' => ['nullable', 'string'],
            'advancedSettings.tentativeEmote' => ['nullable', 'string'],
            'advancedSettings.absenceEmote' => ['nullable', 'string'],
            'advancedSettings.leaderEmote' => ['nullable', 'string'],
            'advancedSettings.signups1Emote' => ['nullable', 'string'],
            'advancedSettings.signups2Emote' => ['nullable', 'string'],
            'advancedSettings.date1Emote' => ['nullable', 'string'],
            'advancedSettings.date2Emote' => ['nullable', 'string'],
            'advancedSettings.time1Emote' => ['nullable', 'string'],
            'advancedSettings.time2Emote' => ['nullable', 'string'],
            'advancedSettings.countdown1Emote' => ['nullable', 'string'],
            'advancedSettings.countdown2Emote' => ['nullable', 'string'],
            'advancedSettings.specresetEmote' => ['nullable', 'string'],
            'advancedSettings.unregisterEmote' => ['nullable', 'string'],
            'advancedSettings.eventType' => ['nullable', 'string'],
            'advancedSettings.reminder' => ['nullable', 'string'],
            'advancedSettings.createDiscordevent' => ['nullable', 'boolean'],
            'advancedSettings.createThread' => ['nullable', 'boolean'],
            'advancedSettings.deleteThread' => ['nullable', 'boolean'],
            'advancedSettings.threadLogging' => ['nullable', 'boolean'],
            'advancedSettings.voiceChannel' => ['nullable', 'string'],
            'advancedSettings.tempVoicechannel' => ['nullable', 'string'],
            'advancedSettings.color' => ['nullable', 'string'],
            'advancedSettings.response' => ['nullable', 'string'],
            'advancedSettings.tempRole' => ['nullable', 'string'],
            'advancedSettings.allowedRoles' => ['nullable', 'string'],
            'advancedSettings.forumTags' => ['nullable', 'string'],
            'advancedSettings.bannedRoles' => ['nullable', 'string'],
            'advancedSettings.optOut' => ['nullable', 'string'],
            'advancedSettings.mentions' => ['nullable', 'string'],
            'advancedSettings.image' => ['nullable', 'string'],
            'advancedSettings.thumbnail' => ['nullable', 'string'],
            'advancedSettings.useNicknames' => ['nullable', 'string'],
            'advancedSettings.text1' => ['nullable', 'string'],
            'advancedSettings.text2' => ['nullable', 'string'],
            'advancedSettings.pollAdd' => ['nullable', 'string'],
            'advancedSettings.pollAddReq' => ['nullable', 'string'],
            'advancedSettings.tpDeletion' => ['nullable', 'string'],
            'advancedSettings.tpProfile' => ['nullable', 'string'],
            'advancedSettings.tpWinMin' => ['nullable', 'integer', 'min:0'],
            'advancedSettings.trInclude' => ['nullable', 'string'],
            'advancedSettings.dkpAmount' => ['nullable', 'string'],
            'advancedSettings.dkpDelay' => ['nullable', 'string'],
            'advancedSettings.dkpInclude' => ['nullable', 'string'],
            'advancedSettings.notesEnabled' => ['nullable', 'boolean'],
            'advancedSettings.hideComp' => ['nullable', 'boolean'],
        ];
    }
}
