<?php

namespace Database\Seeders\LootCouncil;

use App\Models\LootCouncil\Item;
use Illuminate\Database\Seeder;

class ItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            ['id' => 28453, 'raid_id' => 1, 'boss_id' => 1, 'group' => null],
            ['id' => 28454, 'raid_id' => 1, 'boss_id' => 1, 'group' => null],
            ['id' => 28477, 'raid_id' => 1, 'boss_id' => 1, 'group' => null],
            ['id' => 28502, 'raid_id' => 1, 'boss_id' => 1, 'group' => null],
            ['id' => 28503, 'raid_id' => 1, 'boss_id' => 1, 'group' => null],
            ['id' => 28504, 'raid_id' => 1, 'boss_id' => 1, 'group' => null],
            ['id' => 28505, 'raid_id' => 1, 'boss_id' => 1, 'group' => null],
            ['id' => 28506, 'raid_id' => 1, 'boss_id' => 1, 'group' => null],
            ['id' => 28507, 'raid_id' => 1, 'boss_id' => 1, 'group' => null],
            ['id' => 28508, 'raid_id' => 1, 'boss_id' => 1, 'group' => null],
            ['id' => 28509, 'raid_id' => 1, 'boss_id' => 1, 'group' => null],
            ['id' => 28510, 'raid_id' => 1, 'boss_id' => 1, 'group' => null],
            ['id' => 28511, 'raid_id' => 1, 'boss_id' => 4, 'group' => null],
            ['id' => 28512, 'raid_id' => 1, 'boss_id' => 4, 'group' => null],
            ['id' => 28514, 'raid_id' => 1, 'boss_id' => 4, 'group' => null],
            ['id' => 28515, 'raid_id' => 1, 'boss_id' => 4, 'group' => null],
            ['id' => 28516, 'raid_id' => 1, 'boss_id' => 4, 'group' => null],
            ['id' => 28517, 'raid_id' => 1, 'boss_id' => 4, 'group' => null],
            ['id' => 28518, 'raid_id' => 1, 'boss_id' => 4, 'group' => null],
            ['id' => 28519, 'raid_id' => 1, 'boss_id' => 4, 'group' => null],
            ['id' => 28520, 'raid_id' => 1, 'boss_id' => 4, 'group' => null],
            ['id' => 28521, 'raid_id' => 1, 'boss_id' => 4, 'group' => null],
            ['id' => 28522, 'raid_id' => 1, 'boss_id' => 4, 'group' => null],
            ['id' => 28523, 'raid_id' => 1, 'boss_id' => 4, 'group' => null],
            ['id' => 28524, 'raid_id' => 1, 'boss_id' => 3, 'group' => null],
            ['id' => 28525, 'raid_id' => 1, 'boss_id' => 3, 'group' => null],
            ['id' => 28528, 'raid_id' => 1, 'boss_id' => 3, 'group' => null],
            ['id' => 28529, 'raid_id' => 1, 'boss_id' => 3, 'group' => null],
            ['id' => 28530, 'raid_id' => 1, 'boss_id' => 3, 'group' => null],
            ['id' => 28545, 'raid_id' => 1, 'boss_id' => 3, 'group' => null],
            ['id' => 28565, 'raid_id' => 1, 'boss_id' => 3, 'group' => null],
            ['id' => 28566, 'raid_id' => 1, 'boss_id' => 3, 'group' => null],
            ['id' => 28567, 'raid_id' => 1, 'boss_id' => 3, 'group' => null],
            ['id' => 28568, 'raid_id' => 1, 'boss_id' => 3, 'group' => null],
            ['id' => 28569, 'raid_id' => 1, 'boss_id' => 3, 'group' => null],
            ['id' => 28570, 'raid_id' => 1, 'boss_id' => 3, 'group' => null],
            ['id' => 28572, 'raid_id' => 1, 'boss_id' => 5, 'group' => 'Romulo and Julianne'],
            ['id' => 28573, 'raid_id' => 1, 'boss_id' => 5, 'group' => 'Romulo and Julianne'],
            ['id' => 28578, 'raid_id' => 1, 'boss_id' => 5, 'group' => 'Romulo and Julianne'],
            ['id' => 28579, 'raid_id' => 1, 'boss_id' => 5, 'group' => 'Romulo and Julianne'],
            ['id' => 28581, 'raid_id' => 1, 'boss_id' => 5, 'group' => 'The Big Bad Wolf'],
            ['id' => 28582, 'raid_id' => 1, 'boss_id' => 5, 'group' => 'The Big Bad Wolf'],
            ['id' => 28583, 'raid_id' => 1, 'boss_id' => 5, 'group' => 'The Big Bad Wolf'],
            ['id' => 28584, 'raid_id' => 1, 'boss_id' => 5, 'group' => 'The Big Bad Wolf'],
            ['id' => 28585, 'raid_id' => 1, 'boss_id' => 5, 'group' => 'The Wizard of Oz'],
            ['id' => 28586, 'raid_id' => 1, 'boss_id' => 5, 'group' => 'The Wizard of Oz'],
            ['id' => 28587, 'raid_id' => 1, 'boss_id' => 5, 'group' => 'The Wizard of Oz'],
            ['id' => 28588, 'raid_id' => 1, 'boss_id' => 5, 'group' => 'The Wizard of Oz'],
            ['id' => 28589, 'raid_id' => 1, 'boss_id' => 5, 'group' => 'Shared loot'],
            ['id' => 28590, 'raid_id' => 1, 'boss_id' => 5, 'group' => 'Shared loot'],
            ['id' => 28591, 'raid_id' => 1, 'boss_id' => 5, 'group' => 'Shared loot'],
            ['id' => 28592, 'raid_id' => 1, 'boss_id' => 5, 'group' => 'Shared loot'],
            ['id' => 28593, 'raid_id' => 1, 'boss_id' => 5, 'group' => 'Shared loot'],
            ['id' => 28594, 'raid_id' => 1, 'boss_id' => 5, 'group' => 'Shared loot'],
            ['id' => 28597, 'raid_id' => 1, 'boss_id' => 6, 'group' => null],
            ['id' => 28599, 'raid_id' => 1, 'boss_id' => 6, 'group' => null],
            ['id' => 28600, 'raid_id' => 1, 'boss_id' => 6, 'group' => null],
            ['id' => 28601, 'raid_id' => 1, 'boss_id' => 6, 'group' => null],
            ['id' => 28602, 'raid_id' => 1, 'boss_id' => 6, 'group' => null],
            ['id' => 28603, 'raid_id' => 1, 'boss_id' => 6, 'group' => null],
            ['id' => 28604, 'raid_id' => 1, 'boss_id' => 6, 'group' => null],
            ['id' => 28606, 'raid_id' => 1, 'boss_id' => 6, 'group' => null],
            ['id' => 28608, 'raid_id' => 1, 'boss_id' => 6, 'group' => null],
            ['id' => 28609, 'raid_id' => 1, 'boss_id' => 6, 'group' => null],
            ['id' => 28610, 'raid_id' => 1, 'boss_id' => 6, 'group' => null],
            ['id' => 28611, 'raid_id' => 1, 'boss_id' => 6, 'group' => null],
            ['id' => 28612, 'raid_id' => 1, 'boss_id' => 7, 'group' => null],
            ['id' => 28621, 'raid_id' => 1, 'boss_id' => 7, 'group' => null],
            ['id' => 28631, 'raid_id' => 1, 'boss_id' => 7, 'group' => null],
            ['id' => 28633, 'raid_id' => 1, 'boss_id' => 7, 'group' => null],
            ['id' => 28647, 'raid_id' => 1, 'boss_id' => 7, 'group' => null],
            ['id' => 28649, 'raid_id' => 1, 'boss_id' => 7, 'group' => null],
            ['id' => 28652, 'raid_id' => 1, 'boss_id' => 8, 'group' => null],
            ['id' => 28653, 'raid_id' => 1, 'boss_id' => 8, 'group' => null],
            ['id' => 28654, 'raid_id' => 1, 'boss_id' => 8, 'group' => null],
            ['id' => 28655, 'raid_id' => 1, 'boss_id' => 8, 'group' => null],
            ['id' => 28656, 'raid_id' => 1, 'boss_id' => 8, 'group' => null],
            ['id' => 28657, 'raid_id' => 1, 'boss_id' => 8, 'group' => null],
            ['id' => 28658, 'raid_id' => 1, 'boss_id' => 8, 'group' => null],
            ['id' => 28659, 'raid_id' => 1, 'boss_id' => 8, 'group' => null],
            ['id' => 28660, 'raid_id' => 1, 'boss_id' => 8, 'group' => null],
            ['id' => 28661, 'raid_id' => 1, 'boss_id' => 8, 'group' => null],
            ['id' => 28662, 'raid_id' => 1, 'boss_id' => 8, 'group' => null],
            ['id' => 28663, 'raid_id' => 1, 'boss_id' => 9, 'group' => null],
            ['id' => 28666, 'raid_id' => 1, 'boss_id' => 9, 'group' => null],
            ['id' => 28669, 'raid_id' => 1, 'boss_id' => 9, 'group' => null],
            ['id' => 28670, 'raid_id' => 1, 'boss_id' => 9, 'group' => null],
            ['id' => 28671, 'raid_id' => 1, 'boss_id' => 9, 'group' => null],
            ['id' => 28672, 'raid_id' => 1, 'boss_id' => 9, 'group' => null],
            ['id' => 28673, 'raid_id' => 1, 'boss_id' => 9, 'group' => null],
            ['id' => 28674, 'raid_id' => 1, 'boss_id' => 9, 'group' => null],
            ['id' => 28675, 'raid_id' => 1, 'boss_id' => 9, 'group' => null],
            ['id' => 28726, 'raid_id' => 1, 'boss_id' => 9, 'group' => null],
            ['id' => 28727, 'raid_id' => 1, 'boss_id' => 9, 'group' => null],
            ['id' => 28728, 'raid_id' => 1, 'boss_id' => 9, 'group' => null],
            ['id' => 28729, 'raid_id' => 1, 'boss_id' => 10, 'group' => null],
            ['id' => 28730, 'raid_id' => 1, 'boss_id' => 10, 'group' => null],
            ['id' => 28731, 'raid_id' => 1, 'boss_id' => 10, 'group' => null],
            ['id' => 28732, 'raid_id' => 1, 'boss_id' => 10, 'group' => null],
            ['id' => 28733, 'raid_id' => 1, 'boss_id' => 10, 'group' => null],
            ['id' => 28734, 'raid_id' => 1, 'boss_id' => 10, 'group' => null],
            ['id' => 28735, 'raid_id' => 1, 'boss_id' => 10, 'group' => null],
            ['id' => 28740, 'raid_id' => 1, 'boss_id' => 10, 'group' => null],
            ['id' => 28741, 'raid_id' => 1, 'boss_id' => 10, 'group' => null],
            ['id' => 28742, 'raid_id' => 1, 'boss_id' => 10, 'group' => null],
            ['id' => 28743, 'raid_id' => 1, 'boss_id' => 10, 'group' => null],
            ['id' => 28744, 'raid_id' => 1, 'boss_id' => 10, 'group' => null],
            ['id' => 28745, 'raid_id' => 1, 'boss_id' => 11, 'group' => null],
            ['id' => 28746, 'raid_id' => 1, 'boss_id' => 11, 'group' => null],
            ['id' => 28747, 'raid_id' => 1, 'boss_id' => 11, 'group' => null],
            ['id' => 28748, 'raid_id' => 1, 'boss_id' => 11, 'group' => null],
            ['id' => 28749, 'raid_id' => 1, 'boss_id' => 11, 'group' => null],
            ['id' => 28750, 'raid_id' => 1, 'boss_id' => 11, 'group' => null],
            ['id' => 28751, 'raid_id' => 1, 'boss_id' => 11, 'group' => null],
            ['id' => 28752, 'raid_id' => 1, 'boss_id' => 11, 'group' => null],
            ['id' => 28753, 'raid_id' => 1, 'boss_id' => 11, 'group' => null],
            ['id' => 28754, 'raid_id' => 1, 'boss_id' => 11, 'group' => null],
            ['id' => 28755, 'raid_id' => 1, 'boss_id' => 11, 'group' => null],
            ['id' => 28756, 'raid_id' => 1, 'boss_id' => 11, 'group' => null],
            ['id' => 28757, 'raid_id' => 1, 'boss_id' => 12, 'group' => null],
            ['id' => 28762, 'raid_id' => 1, 'boss_id' => 12, 'group' => null],
            ['id' => 28763, 'raid_id' => 1, 'boss_id' => 12, 'group' => null],
            ['id' => 28764, 'raid_id' => 1, 'boss_id' => 12, 'group' => null],
            ['id' => 28765, 'raid_id' => 1, 'boss_id' => 12, 'group' => null],
            ['id' => 28766, 'raid_id' => 1, 'boss_id' => 12, 'group' => null],
            ['id' => 28767, 'raid_id' => 1, 'boss_id' => 12, 'group' => null],
            ['id' => 28768, 'raid_id' => 1, 'boss_id' => 12, 'group' => null],
            ['id' => 28770, 'raid_id' => 1, 'boss_id' => 12, 'group' => null],
            ['id' => 28771, 'raid_id' => 1, 'boss_id' => 12, 'group' => null],
            ['id' => 28772, 'raid_id' => 1, 'boss_id' => 12, 'group' => null],
            ['id' => 28773, 'raid_id' => 1, 'boss_id' => 12, 'group' => null],
            ['id' => 28774, 'raid_id' => 3, 'boss_id' => 15, 'group' => null],
            ['id' => 28775, 'raid_id' => 3, 'boss_id' => 15, 'group' => null],
            ['id' => 28776, 'raid_id' => 3, 'boss_id' => 15, 'group' => null],
            ['id' => 28777, 'raid_id' => 3, 'boss_id' => 15, 'group' => null],
            ['id' => 28778, 'raid_id' => 3, 'boss_id' => 15, 'group' => null],
            ['id' => 28779, 'raid_id' => 3, 'boss_id' => 15, 'group' => null],
            ['id' => 28780, 'raid_id' => 3, 'boss_id' => 15, 'group' => null],
            ['id' => 28781, 'raid_id' => 3, 'boss_id' => 15, 'group' => null],
            ['id' => 28782, 'raid_id' => 3, 'boss_id' => 15, 'group' => null],
            ['id' => 28783, 'raid_id' => 3, 'boss_id' => 15, 'group' => null],
            ['id' => 28785, 'raid_id' => 1, 'boss_id' => 8, 'group' => null],
            ['id' => 28789, 'raid_id' => 3, 'boss_id' => 15, 'group' => null],
            ['id' => 28794, 'raid_id' => 2, 'boss_id' => 14, 'group' => null],
            ['id' => 28795, 'raid_id' => 2, 'boss_id' => 13, 'group' => null],
            ['id' => 28796, 'raid_id' => 2, 'boss_id' => 13, 'group' => null],
            ['id' => 28797, 'raid_id' => 2, 'boss_id' => 13, 'group' => null],
            ['id' => 28799, 'raid_id' => 2, 'boss_id' => 13, 'group' => null],
            ['id' => 28800, 'raid_id' => 2, 'boss_id' => 13, 'group' => null],
            ['id' => 28801, 'raid_id' => 2, 'boss_id' => 13, 'group' => null],
            ['id' => 28802, 'raid_id' => 2, 'boss_id' => 14, 'group' => null],
            ['id' => 28803, 'raid_id' => 2, 'boss_id' => 14, 'group' => null],
            ['id' => 28804, 'raid_id' => 2, 'boss_id' => 14, 'group' => null],
            ['id' => 28810, 'raid_id' => 2, 'boss_id' => 14, 'group' => null],
            ['id' => 28822, 'raid_id' => 2, 'boss_id' => 14, 'group' => null],
            ['id' => 28823, 'raid_id' => 2, 'boss_id' => 14, 'group' => null],
            ['id' => 28824, 'raid_id' => 2, 'boss_id' => 14, 'group' => null],
            ['id' => 28825, 'raid_id' => 2, 'boss_id' => 14, 'group' => null],
            ['id' => 28826, 'raid_id' => 2, 'boss_id' => 14, 'group' => null],
            ['id' => 28827, 'raid_id' => 2, 'boss_id' => 14, 'group' => null],
            ['id' => 28828, 'raid_id' => 2, 'boss_id' => 14, 'group' => null],
            ['id' => 28830, 'raid_id' => 2, 'boss_id' => 14, 'group' => null],
            ['id' => 29458, 'raid_id' => 3, 'boss_id' => 15, 'group' => null],
            ['id' => 29753, 'raid_id' => 3, 'boss_id' => 15, 'group' => 'Tier 4 tokens'],
            ['id' => 29754, 'raid_id' => 3, 'boss_id' => 15, 'group' => 'Tier 4 tokens'],
            ['id' => 29755, 'raid_id' => 3, 'boss_id' => 15, 'group' => 'Tier 4 tokens'],
            ['id' => 29756, 'raid_id' => 1, 'boss_id' => 7, 'group' => 'Tier 4 tokens'],
            ['id' => 29757, 'raid_id' => 1, 'boss_id' => 7, 'group' => 'Tier 4 tokens'],
            ['id' => 29758, 'raid_id' => 1, 'boss_id' => 7, 'group' => 'Tier 4 tokens'],
            ['id' => 29759, 'raid_id' => 1, 'boss_id' => 12, 'group' => 'Tier 4 tokens'],
            ['id' => 29760, 'raid_id' => 1, 'boss_id' => 12, 'group' => 'Tier 4 tokens'],
            ['id' => 29761, 'raid_id' => 1, 'boss_id' => 12, 'group' => 'Tier 4 tokens'],
            ['id' => 29762, 'raid_id' => 2, 'boss_id' => 13, 'group' => 'Tier 4 tokens'],
            ['id' => 29763, 'raid_id' => 2, 'boss_id' => 13, 'group' => 'Tier 4 tokens'],
            ['id' => 29764, 'raid_id' => 2, 'boss_id' => 13, 'group' => 'Tier 4 tokens'],
            ['id' => 29765, 'raid_id' => 2, 'boss_id' => 14, 'group' => 'Tier 4 tokens'],
            ['id' => 29766, 'raid_id' => 2, 'boss_id' => 14, 'group' => 'Tier 4 tokens'],
            ['id' => 29767, 'raid_id' => 2, 'boss_id' => 14, 'group' => 'Tier 4 tokens'],
            ['id' => 29918, 'raid_id' => 5, 'boss_id' => 22, 'group' => null],
            ['id' => 29920, 'raid_id' => 5, 'boss_id' => 22, 'group' => null],
            ['id' => 29921, 'raid_id' => 5, 'boss_id' => 22, 'group' => null],
            ['id' => 29922, 'raid_id' => 5, 'boss_id' => 22, 'group' => null],
            ['id' => 29923, 'raid_id' => 5, 'boss_id' => 22, 'group' => null],
            ['id' => 29924, 'raid_id' => 5, 'boss_id' => 22, 'group' => null],
            ['id' => 29925, 'raid_id' => 5, 'boss_id' => 22, 'group' => null],
            ['id' => 29947, 'raid_id' => 5, 'boss_id' => 22, 'group' => null],
            ['id' => 29948, 'raid_id' => 5, 'boss_id' => 22, 'group' => null],
            ['id' => 29949, 'raid_id' => 5, 'boss_id' => 22, 'group' => null],
            ['id' => 29950, 'raid_id' => 5, 'boss_id' => 24, 'group' => null],
            ['id' => 29951, 'raid_id' => 5, 'boss_id' => 24, 'group' => null],
            ['id' => 29962, 'raid_id' => 5, 'boss_id' => 24, 'group' => null],
            ['id' => 29965, 'raid_id' => 5, 'boss_id' => 24, 'group' => null],
            ['id' => 29966, 'raid_id' => 5, 'boss_id' => 24, 'group' => null],
            ['id' => 29972, 'raid_id' => 5, 'boss_id' => 24, 'group' => null],
            ['id' => 29976, 'raid_id' => 5, 'boss_id' => 24, 'group' => null],
            ['id' => 29977, 'raid_id' => 5, 'boss_id' => 24, 'group' => null],
            ['id' => 29981, 'raid_id' => 5, 'boss_id' => 24, 'group' => null],
            ['id' => 29982, 'raid_id' => 5, 'boss_id' => 24, 'group' => null],
            ['id' => 29983, 'raid_id' => 5, 'boss_id' => 23, 'group' => null],
            ['id' => 29984, 'raid_id' => 5, 'boss_id' => 23, 'group' => null],
            ['id' => 29985, 'raid_id' => 5, 'boss_id' => 23, 'group' => null],
            ['id' => 29986, 'raid_id' => 5, 'boss_id' => 23, 'group' => null],
            ['id' => 29987, 'raid_id' => 5, 'boss_id' => 25, 'group' => null],
            ['id' => 29988, 'raid_id' => 5, 'boss_id' => 25, 'group' => null],
            ['id' => 29989, 'raid_id' => 5, 'boss_id' => 25, 'group' => null],
            ['id' => 29990, 'raid_id' => 5, 'boss_id' => 25, 'group' => null],
            ['id' => 29991, 'raid_id' => 5, 'boss_id' => 25, 'group' => null],
            ['id' => 29992, 'raid_id' => 5, 'boss_id' => 25, 'group' => null],
            ['id' => 29993, 'raid_id' => 5, 'boss_id' => 25, 'group' => null],
            ['id' => 29994, 'raid_id' => 5, 'boss_id' => 25, 'group' => null],
            ['id' => 29995, 'raid_id' => 5, 'boss_id' => 25, 'group' => null],
            ['id' => 29996, 'raid_id' => 5, 'boss_id' => 25, 'group' => null],
            ['id' => 29997, 'raid_id' => 5, 'boss_id' => 25, 'group' => null],
            ['id' => 29998, 'raid_id' => 5, 'boss_id' => 25, 'group' => null],
            ['id' => 30008, 'raid_id' => 4, 'boss_id' => 20, 'group' => null],
            ['id' => 30020, 'raid_id' => 5, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 30021, 'raid_id' => 4, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 30022, 'raid_id' => 4, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 30023, 'raid_id' => 4, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 30024, 'raid_id' => 5, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 30026, 'raid_id' => 5, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 30027, 'raid_id' => 4, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 30028, 'raid_id' => 5, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 30029, 'raid_id' => 5, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 30030, 'raid_id' => 5, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 30047, 'raid_id' => 4, 'boss_id' => 16, 'group' => null],
            ['id' => 30048, 'raid_id' => 4, 'boss_id' => 16, 'group' => null],
            ['id' => 30049, 'raid_id' => 4, 'boss_id' => 16, 'group' => null],
            ['id' => 30050, 'raid_id' => 4, 'boss_id' => 16, 'group' => null],
            ['id' => 30052, 'raid_id' => 4, 'boss_id' => 16, 'group' => null],
            ['id' => 30053, 'raid_id' => 4, 'boss_id' => 16, 'group' => null],
            ['id' => 30054, 'raid_id' => 4, 'boss_id' => 16, 'group' => null],
            ['id' => 30055, 'raid_id' => 4, 'boss_id' => 16, 'group' => null],
            ['id' => 30056, 'raid_id' => 4, 'boss_id' => 16, 'group' => null],
            ['id' => 30057, 'raid_id' => 4, 'boss_id' => 17, 'group' => null],
            ['id' => 30058, 'raid_id' => 4, 'boss_id' => 17, 'group' => null],
            ['id' => 30059, 'raid_id' => 4, 'boss_id' => 17, 'group' => null],
            ['id' => 30060, 'raid_id' => 4, 'boss_id' => 17, 'group' => null],
            ['id' => 30061, 'raid_id' => 4, 'boss_id' => 17, 'group' => null],
            ['id' => 30062, 'raid_id' => 4, 'boss_id' => 17, 'group' => null],
            ['id' => 30064, 'raid_id' => 4, 'boss_id' => 17, 'group' => null],
            ['id' => 30065, 'raid_id' => 4, 'boss_id' => 17, 'group' => null],
            ['id' => 30066, 'raid_id' => 4, 'boss_id' => 17, 'group' => null],
            ['id' => 30067, 'raid_id' => 4, 'boss_id' => 17, 'group' => null],
            ['id' => 30068, 'raid_id' => 4, 'boss_id' => 20, 'group' => null],
            ['id' => 30075, 'raid_id' => 4, 'boss_id' => 20, 'group' => null],
            ['id' => 30079, 'raid_id' => 4, 'boss_id' => 20, 'group' => null],
            ['id' => 30080, 'raid_id' => 4, 'boss_id' => 20, 'group' => null],
            ['id' => 30081, 'raid_id' => 4, 'boss_id' => 20, 'group' => null],
            ['id' => 30082, 'raid_id' => 4, 'boss_id' => 20, 'group' => null],
            ['id' => 30083, 'raid_id' => 4, 'boss_id' => 20, 'group' => null],
            ['id' => 30084, 'raid_id' => 4, 'boss_id' => 20, 'group' => null],
            ['id' => 30085, 'raid_id' => 4, 'boss_id' => 20, 'group' => null],
            ['id' => 30090, 'raid_id' => 4, 'boss_id' => 19, 'group' => null],
            ['id' => 30091, 'raid_id' => 4, 'boss_id' => 18, 'group' => null],
            ['id' => 30092, 'raid_id' => 4, 'boss_id' => 18, 'group' => null],
            ['id' => 30095, 'raid_id' => 4, 'boss_id' => 18, 'group' => null],
            ['id' => 30096, 'raid_id' => 4, 'boss_id' => 18, 'group' => null],
            ['id' => 30097, 'raid_id' => 4, 'boss_id' => 18, 'group' => null],
            ['id' => 30098, 'raid_id' => 4, 'boss_id' => 20, 'group' => null],
            ['id' => 30099, 'raid_id' => 4, 'boss_id' => 19, 'group' => null],
            ['id' => 30100, 'raid_id' => 4, 'boss_id' => 19, 'group' => null],
            ['id' => 30101, 'raid_id' => 4, 'boss_id' => 19, 'group' => null],
            ['id' => 30102, 'raid_id' => 4, 'boss_id' => 21, 'group' => null],
            ['id' => 30103, 'raid_id' => 4, 'boss_id' => 21, 'group' => null],
            ['id' => 30104, 'raid_id' => 4, 'boss_id' => 21, 'group' => null],
            ['id' => 30105, 'raid_id' => 4, 'boss_id' => 21, 'group' => null],
            ['id' => 30106, 'raid_id' => 4, 'boss_id' => 21, 'group' => null],
            ['id' => 30107, 'raid_id' => 4, 'boss_id' => 21, 'group' => null],
            ['id' => 30108, 'raid_id' => 4, 'boss_id' => 21, 'group' => null],
            ['id' => 30109, 'raid_id' => 4, 'boss_id' => 21, 'group' => null],
            ['id' => 30110, 'raid_id' => 4, 'boss_id' => 21, 'group' => null],
            ['id' => 30111, 'raid_id' => 4, 'boss_id' => 21, 'group' => null],
            ['id' => 30112, 'raid_id' => 4, 'boss_id' => 21, 'group' => null],
            ['id' => 30236, 'raid_id' => 5, 'boss_id' => 25, 'group' => 'Tier 5 tokens'],
            ['id' => 30237, 'raid_id' => 5, 'boss_id' => 25, 'group' => 'Tier 5 tokens'],
            ['id' => 30238, 'raid_id' => 5, 'boss_id' => 25, 'group' => 'Tier 5 tokens'],
            ['id' => 30239, 'raid_id' => 4, 'boss_id' => 18, 'group' => 'Tier 5 tokens'],
            ['id' => 30240, 'raid_id' => 4, 'boss_id' => 18, 'group' => 'Tier 5 tokens'],
            ['id' => 30241, 'raid_id' => 4, 'boss_id' => 18, 'group' => 'Tier 5 tokens'],
            ['id' => 30242, 'raid_id' => 4, 'boss_id' => 21, 'group' => 'Tier 5 tokens'],
            ['id' => 30243, 'raid_id' => 4, 'boss_id' => 21, 'group' => 'Tier 5 tokens'],
            ['id' => 30244, 'raid_id' => 4, 'boss_id' => 21, 'group' => 'Tier 5 tokens'],
            ['id' => 30245, 'raid_id' => 4, 'boss_id' => 19, 'group' => 'Tier 5 tokens'],
            ['id' => 30246, 'raid_id' => 4, 'boss_id' => 19, 'group' => 'Tier 5 tokens'],
            ['id' => 30247, 'raid_id' => 4, 'boss_id' => 19, 'group' => 'Tier 5 tokens'],
            ['id' => 30248, 'raid_id' => 5, 'boss_id' => 23, 'group' => 'Tier 5 tokens'],
            ['id' => 30249, 'raid_id' => 5, 'boss_id' => 23, 'group' => 'Tier 5 tokens'],
            ['id' => 30250, 'raid_id' => 5, 'boss_id' => 23, 'group' => 'Tier 5 tokens'],
            ['id' => 30446, 'raid_id' => 5, 'boss_id' => 24, 'group' => null],
            ['id' => 30447, 'raid_id' => 5, 'boss_id' => 22, 'group' => null],
            ['id' => 30448, 'raid_id' => 5, 'boss_id' => 22, 'group' => null],
            ['id' => 30449, 'raid_id' => 5, 'boss_id' => 24, 'group' => null],
            ['id' => 30450, 'raid_id' => 5, 'boss_id' => 23, 'group' => null],
            ['id' => 30619, 'raid_id' => 5, 'boss_id' => 23, 'group' => null],
            ['id' => 30620, 'raid_id' => 4, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 30621, 'raid_id' => 4, 'boss_id' => 21, 'group' => null],
            ['id' => 30626, 'raid_id' => 4, 'boss_id' => 19, 'group' => null],
            ['id' => 30627, 'raid_id' => 4, 'boss_id' => 18, 'group' => null],
            ['id' => 30629, 'raid_id' => 4, 'boss_id' => 16, 'group' => null],
            ['id' => 30641, 'raid_id' => 1, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 30642, 'raid_id' => 1, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 30643, 'raid_id' => 1, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 30644, 'raid_id' => 1, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 30663, 'raid_id' => 4, 'boss_id' => 19, 'group' => null],
            ['id' => 30664, 'raid_id' => 4, 'boss_id' => 16, 'group' => null],
            ['id' => 30665, 'raid_id' => 4, 'boss_id' => 17, 'group' => null],
            ['id' => 30666, 'raid_id' => 1, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 30667, 'raid_id' => 1, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 30668, 'raid_id' => 1, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 30673, 'raid_id' => 1, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 30674, 'raid_id' => 1, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 30675, 'raid_id' => 1, 'boss_id' => 2, 'group' => 'Hyakiss the Lurker'],
            ['id' => 30676, 'raid_id' => 1, 'boss_id' => 2, 'group' => 'Hyakiss the Lurker'],
            ['id' => 30677, 'raid_id' => 1, 'boss_id' => 2, 'group' => 'Hyakiss the Lurker'],
            ['id' => 30678, 'raid_id' => 1, 'boss_id' => 2, 'group' => 'Hyakiss the Lurker'],
            ['id' => 30680, 'raid_id' => 1, 'boss_id' => 2, 'group' => 'Shadikith the Glider'],
            ['id' => 30681, 'raid_id' => 1, 'boss_id' => 2, 'group' => 'Shadikith the Glider'],
            ['id' => 30682, 'raid_id' => 1, 'boss_id' => 2, 'group' => 'Shadikith the Glider'],
            ['id' => 30683, 'raid_id' => 1, 'boss_id' => 2, 'group' => 'Shadikith the Glider'],
            ['id' => 30684, 'raid_id' => 1, 'boss_id' => 2, 'group' => 'Rokad the Ravager'],
            ['id' => 30685, 'raid_id' => 1, 'boss_id' => 2, 'group' => 'Rokad the Ravager'],
            ['id' => 30686, 'raid_id' => 1, 'boss_id' => 2, 'group' => 'Rokad the Ravager'],
            ['id' => 30687, 'raid_id' => 1, 'boss_id' => 2, 'group' => 'Rokad the Ravager'],
            ['id' => 30720, 'raid_id' => 4, 'boss_id' => 20, 'group' => null],
            ['id' => 30861, 'raid_id' => 6, 'boss_id' => 26, 'group' => null],
            ['id' => 30862, 'raid_id' => 6, 'boss_id' => 26, 'group' => null],
            ['id' => 30863, 'raid_id' => 6, 'boss_id' => 26, 'group' => null],
            ['id' => 30864, 'raid_id' => 6, 'boss_id' => 26, 'group' => null],
            ['id' => 30865, 'raid_id' => 6, 'boss_id' => 26, 'group' => null],
            ['id' => 30866, 'raid_id' => 6, 'boss_id' => 26, 'group' => null],
            ['id' => 30868, 'raid_id' => 6, 'boss_id' => 26, 'group' => null],
            ['id' => 30869, 'raid_id' => 6, 'boss_id' => 26, 'group' => null],
            ['id' => 30870, 'raid_id' => 6, 'boss_id' => 26, 'group' => null],
            ['id' => 30871, 'raid_id' => 6, 'boss_id' => 26, 'group' => null],
            ['id' => 30872, 'raid_id' => 6, 'boss_id' => 26, 'group' => null],
            ['id' => 30873, 'raid_id' => 6, 'boss_id' => 26, 'group' => null],
            ['id' => 30874, 'raid_id' => 6, 'boss_id' => 27, 'group' => null],
            ['id' => 30878, 'raid_id' => 6, 'boss_id' => 27, 'group' => null],
            ['id' => 30879, 'raid_id' => 6, 'boss_id' => 27, 'group' => null],
            ['id' => 30880, 'raid_id' => 6, 'boss_id' => 27, 'group' => null],
            ['id' => 30881, 'raid_id' => 6, 'boss_id' => 27, 'group' => null],
            ['id' => 30882, 'raid_id' => 6, 'boss_id' => 27, 'group' => null],
            ['id' => 30883, 'raid_id' => 6, 'boss_id' => 27, 'group' => null],
            ['id' => 30884, 'raid_id' => 6, 'boss_id' => 27, 'group' => null],
            ['id' => 30885, 'raid_id' => 6, 'boss_id' => 27, 'group' => null],
            ['id' => 30886, 'raid_id' => 6, 'boss_id' => 27, 'group' => null],
            ['id' => 30887, 'raid_id' => 6, 'boss_id' => 27, 'group' => null],
            ['id' => 30888, 'raid_id' => 6, 'boss_id' => 27, 'group' => null],
            ['id' => 30889, 'raid_id' => 6, 'boss_id' => 28, 'group' => null],
            ['id' => 30891, 'raid_id' => 6, 'boss_id' => 28, 'group' => null],
            ['id' => 30892, 'raid_id' => 6, 'boss_id' => 28, 'group' => null],
            ['id' => 30893, 'raid_id' => 6, 'boss_id' => 28, 'group' => null],
            ['id' => 30894, 'raid_id' => 6, 'boss_id' => 28, 'group' => null],
            ['id' => 30895, 'raid_id' => 6, 'boss_id' => 28, 'group' => null],
            ['id' => 30896, 'raid_id' => 6, 'boss_id' => 29, 'group' => null],
            ['id' => 30897, 'raid_id' => 6, 'boss_id' => 29, 'group' => null],
            ['id' => 30898, 'raid_id' => 6, 'boss_id' => 29, 'group' => null],
            ['id' => 30899, 'raid_id' => 6, 'boss_id' => 29, 'group' => null],
            ['id' => 30900, 'raid_id' => 6, 'boss_id' => 29, 'group' => null],
            ['id' => 30901, 'raid_id' => 6, 'boss_id' => 29, 'group' => null],
            ['id' => 30902, 'raid_id' => 6, 'boss_id' => 30, 'group' => null],
            ['id' => 30903, 'raid_id' => 6, 'boss_id' => 30, 'group' => null],
            ['id' => 30904, 'raid_id' => 6, 'boss_id' => 30, 'group' => null],
            ['id' => 30905, 'raid_id' => 6, 'boss_id' => 30, 'group' => null],
            ['id' => 30906, 'raid_id' => 6, 'boss_id' => 30, 'group' => null],
            ['id' => 30907, 'raid_id' => 6, 'boss_id' => 30, 'group' => null],
            ['id' => 30908, 'raid_id' => 6, 'boss_id' => 30, 'group' => null],
            ['id' => 30909, 'raid_id' => 6, 'boss_id' => 30, 'group' => null],
            ['id' => 30910, 'raid_id' => 6, 'boss_id' => 30, 'group' => null],
            ['id' => 30911, 'raid_id' => 6, 'boss_id' => 30, 'group' => null],
            ['id' => 30912, 'raid_id' => 6, 'boss_id' => 30, 'group' => null],
            ['id' => 30913, 'raid_id' => 6, 'boss_id' => 30, 'group' => null],
            ['id' => 30914, 'raid_id' => 6, 'boss_id' => 28, 'group' => null],
            ['id' => 30915, 'raid_id' => 6, 'boss_id' => 28, 'group' => null],
            ['id' => 30916, 'raid_id' => 6, 'boss_id' => 28, 'group' => null],
            ['id' => 30917, 'raid_id' => 6, 'boss_id' => 28, 'group' => null],
            ['id' => 30918, 'raid_id' => 6, 'boss_id' => 28, 'group' => null],
            ['id' => 30919, 'raid_id' => 6, 'boss_id' => 28, 'group' => null],
            ['id' => 31089, 'raid_id' => 7, 'boss_id' => 39, 'group' => 'Tier 6 tokens'],
            ['id' => 31090, 'raid_id' => 7, 'boss_id' => 39, 'group' => 'Tier 6 tokens'],
            ['id' => 31091, 'raid_id' => 7, 'boss_id' => 39, 'group' => 'Tier 6 tokens'],
            ['id' => 31092, 'raid_id' => 6, 'boss_id' => 29, 'group' => 'Tier 6 tokens'],
            ['id' => 31093, 'raid_id' => 6, 'boss_id' => 29, 'group' => 'Tier 6 tokens'],
            ['id' => 31094, 'raid_id' => 6, 'boss_id' => 29, 'group' => 'Tier 6 tokens'],
            ['id' => 31095, 'raid_id' => 6, 'boss_id' => 30, 'group' => 'Tier 6 tokens'],
            ['id' => 31096, 'raid_id' => 6, 'boss_id' => 30, 'group' => 'Tier 6 tokens'],
            ['id' => 31097, 'raid_id' => 6, 'boss_id' => 30, 'group' => 'Tier 6 tokens'],
            ['id' => 31098, 'raid_id' => 7, 'boss_id' => 38, 'group' => 'Tier 6 tokens'],
            ['id' => 31099, 'raid_id' => 7, 'boss_id' => 38, 'group' => 'Tier 6 tokens'],
            ['id' => 31100, 'raid_id' => 7, 'boss_id' => 38, 'group' => 'Tier 6 tokens'],
            ['id' => 31101, 'raid_id' => 7, 'boss_id' => 37, 'group' => 'Tier 6 tokens'],
            ['id' => 31102, 'raid_id' => 7, 'boss_id' => 37, 'group' => 'Tier 6 tokens'],
            ['id' => 31103, 'raid_id' => 7, 'boss_id' => 37, 'group' => 'Tier 6 tokens'],
            ['id' => 32232, 'raid_id' => 7, 'boss_id' => 31, 'group' => null],
            ['id' => 32234, 'raid_id' => 7, 'boss_id' => 31, 'group' => null],
            ['id' => 32235, 'raid_id' => 7, 'boss_id' => 39, 'group' => null],
            ['id' => 32236, 'raid_id' => 7, 'boss_id' => 31, 'group' => null],
            ['id' => 32237, 'raid_id' => 7, 'boss_id' => 31, 'group' => null],
            ['id' => 32238, 'raid_id' => 7, 'boss_id' => 31, 'group' => null],
            ['id' => 32239, 'raid_id' => 7, 'boss_id' => 31, 'group' => null],
            ['id' => 32240, 'raid_id' => 7, 'boss_id' => 31, 'group' => null],
            ['id' => 32241, 'raid_id' => 7, 'boss_id' => 31, 'group' => null],
            ['id' => 32242, 'raid_id' => 7, 'boss_id' => 31, 'group' => null],
            ['id' => 32243, 'raid_id' => 7, 'boss_id' => 31, 'group' => null],
            ['id' => 32245, 'raid_id' => 7, 'boss_id' => 31, 'group' => null],
            ['id' => 32247, 'raid_id' => 7, 'boss_id' => 31, 'group' => null],
            ['id' => 32248, 'raid_id' => 7, 'boss_id' => 31, 'group' => null],
            ['id' => 32250, 'raid_id' => 7, 'boss_id' => 32, 'group' => null],
            ['id' => 32251, 'raid_id' => 7, 'boss_id' => 32, 'group' => null],
            ['id' => 32252, 'raid_id' => 7, 'boss_id' => 32, 'group' => null],
            ['id' => 32253, 'raid_id' => 7, 'boss_id' => 32, 'group' => null],
            ['id' => 32254, 'raid_id' => 7, 'boss_id' => 32, 'group' => null],
            ['id' => 32255, 'raid_id' => 7, 'boss_id' => 32, 'group' => null],
            ['id' => 32256, 'raid_id' => 7, 'boss_id' => 32, 'group' => null],
            ['id' => 32257, 'raid_id' => 7, 'boss_id' => 32, 'group' => null],
            ['id' => 32258, 'raid_id' => 7, 'boss_id' => 32, 'group' => null],
            ['id' => 32259, 'raid_id' => 7, 'boss_id' => 32, 'group' => null],
            ['id' => 32260, 'raid_id' => 7, 'boss_id' => 32, 'group' => null],
            ['id' => 32261, 'raid_id' => 7, 'boss_id' => 32, 'group' => null],
            ['id' => 32262, 'raid_id' => 7, 'boss_id' => 32, 'group' => null],
            ['id' => 32263, 'raid_id' => 7, 'boss_id' => 33, 'group' => null],
            ['id' => 32264, 'raid_id' => 7, 'boss_id' => 33, 'group' => null],
            ['id' => 32265, 'raid_id' => 7, 'boss_id' => 33, 'group' => null],
            ['id' => 32266, 'raid_id' => 7, 'boss_id' => 33, 'group' => null],
            ['id' => 32267, 'raid_id' => 5, 'boss_id' => 24, 'group' => null],
            ['id' => 32268, 'raid_id' => 7, 'boss_id' => 33, 'group' => null],
            ['id' => 32269, 'raid_id' => 7, 'boss_id' => 36, 'group' => null],
            ['id' => 32270, 'raid_id' => 7, 'boss_id' => 33, 'group' => null],
            ['id' => 32271, 'raid_id' => 7, 'boss_id' => 33, 'group' => null],
            ['id' => 32273, 'raid_id' => 7, 'boss_id' => 33, 'group' => null],
            ['id' => 32275, 'raid_id' => 7, 'boss_id' => 33, 'group' => null],
            ['id' => 32276, 'raid_id' => 7, 'boss_id' => 33, 'group' => null],
            ['id' => 32278, 'raid_id' => 7, 'boss_id' => 33, 'group' => null],
            ['id' => 32279, 'raid_id' => 7, 'boss_id' => 33, 'group' => null],
            ['id' => 32280, 'raid_id' => 7, 'boss_id' => 34, 'group' => null],
            ['id' => 32323, 'raid_id' => 7, 'boss_id' => 34, 'group' => null],
            ['id' => 32324, 'raid_id' => 7, 'boss_id' => 34, 'group' => null],
            ['id' => 32325, 'raid_id' => 7, 'boss_id' => 34, 'group' => null],
            ['id' => 32326, 'raid_id' => 7, 'boss_id' => 34, 'group' => null],
            ['id' => 32327, 'raid_id' => 7, 'boss_id' => 34, 'group' => null],
            ['id' => 32328, 'raid_id' => 7, 'boss_id' => 34, 'group' => null],
            ['id' => 32329, 'raid_id' => 7, 'boss_id' => 34, 'group' => null],
            ['id' => 32330, 'raid_id' => 7, 'boss_id' => 34, 'group' => null],
            ['id' => 32331, 'raid_id' => 7, 'boss_id' => 38, 'group' => null],
            ['id' => 32332, 'raid_id' => 7, 'boss_id' => 35, 'group' => null],
            ['id' => 32333, 'raid_id' => 7, 'boss_id' => 36, 'group' => null],
            ['id' => 32334, 'raid_id' => 7, 'boss_id' => 36, 'group' => null],
            ['id' => 32335, 'raid_id' => 7, 'boss_id' => 36, 'group' => null],
            ['id' => 32336, 'raid_id' => 7, 'boss_id' => 39, 'group' => null],
            ['id' => 32337, 'raid_id' => 7, 'boss_id' => 36, 'group' => null],
            ['id' => 32338, 'raid_id' => 7, 'boss_id' => 36, 'group' => null],
            ['id' => 32339, 'raid_id' => 7, 'boss_id' => 36, 'group' => null],
            ['id' => 32340, 'raid_id' => 7, 'boss_id' => 36, 'group' => null],
            ['id' => 32341, 'raid_id' => 7, 'boss_id' => 36, 'group' => null],
            ['id' => 32342, 'raid_id' => 7, 'boss_id' => 36, 'group' => null],
            ['id' => 32343, 'raid_id' => 7, 'boss_id' => 36, 'group' => null],
            ['id' => 32344, 'raid_id' => 7, 'boss_id' => 36, 'group' => null],
            ['id' => 32345, 'raid_id' => 7, 'boss_id' => 35, 'group' => null],
            ['id' => 32347, 'raid_id' => 7, 'boss_id' => 35, 'group' => null],
            ['id' => 32348, 'raid_id' => 7, 'boss_id' => 34, 'group' => null],
            ['id' => 32349, 'raid_id' => 7, 'boss_id' => 35, 'group' => null],
            ['id' => 32350, 'raid_id' => 7, 'boss_id' => 35, 'group' => null],
            ['id' => 32353, 'raid_id' => 7, 'boss_id' => 35, 'group' => null],
            ['id' => 32354, 'raid_id' => 7, 'boss_id' => 35, 'group' => null],
            ['id' => 32361, 'raid_id' => 7, 'boss_id' => 33, 'group' => null],
            ['id' => 32363, 'raid_id' => 7, 'boss_id' => 35, 'group' => null],
            ['id' => 32365, 'raid_id' => 7, 'boss_id' => 37, 'group' => null],
            ['id' => 32366, 'raid_id' => 7, 'boss_id' => 37, 'group' => null],
            ['id' => 32367, 'raid_id' => 7, 'boss_id' => 37, 'group' => null],
            ['id' => 32368, 'raid_id' => 7, 'boss_id' => 37, 'group' => null],
            ['id' => 32369, 'raid_id' => 7, 'boss_id' => 37, 'group' => null],
            ['id' => 32370, 'raid_id' => 7, 'boss_id' => 37, 'group' => null],
            ['id' => 32373, 'raid_id' => 7, 'boss_id' => 38, 'group' => null],
            ['id' => 32374, 'raid_id' => 7, 'boss_id' => 39, 'group' => null],
            ['id' => 32375, 'raid_id' => 7, 'boss_id' => 39, 'group' => null],
            ['id' => 32376, 'raid_id' => 7, 'boss_id' => 38, 'group' => null],
            ['id' => 32377, 'raid_id' => 7, 'boss_id' => 31, 'group' => null],
            ['id' => 32385, 'raid_id' => 3, 'boss_id' => 15, 'group' => null],
            ['id' => 32405, 'raid_id' => 5, 'boss_id' => 25, 'group' => null],
            ['id' => 32471, 'raid_id' => 7, 'boss_id' => 39, 'group' => null],
            ['id' => 32483, 'raid_id' => 7, 'boss_id' => 39, 'group' => null],
            ['id' => 32496, 'raid_id' => 7, 'boss_id' => 39, 'group' => null],
            ['id' => 32497, 'raid_id' => 7, 'boss_id' => 39, 'group' => null],
            ['id' => 32500, 'raid_id' => 7, 'boss_id' => 39, 'group' => null],
            ['id' => 32501, 'raid_id' => 7, 'boss_id' => 36, 'group' => null],
            ['id' => 32505, 'raid_id' => 7, 'boss_id' => 38, 'group' => null],
            ['id' => 32510, 'raid_id' => 7, 'boss_id' => 34, 'group' => null],
            ['id' => 32512, 'raid_id' => 7, 'boss_id' => 34, 'group' => null],
            ['id' => 32513, 'raid_id' => 7, 'boss_id' => 33, 'group' => null],
            ['id' => 32515, 'raid_id' => 5, 'boss_id' => 23, 'group' => null],
            ['id' => 32516, 'raid_id' => 4, 'boss_id' => 16, 'group' => null],
            ['id' => 32517, 'raid_id' => 7, 'boss_id' => 35, 'group' => null],
            ['id' => 32518, 'raid_id' => 7, 'boss_id' => 38, 'group' => null],
            ['id' => 32519, 'raid_id' => 7, 'boss_id' => 38, 'group' => null],
            ['id' => 32521, 'raid_id' => 7, 'boss_id' => 39, 'group' => null],
            ['id' => 32524, 'raid_id' => 7, 'boss_id' => 39, 'group' => null],
            ['id' => 32525, 'raid_id' => 7, 'boss_id' => 39, 'group' => null],
            ['id' => 32526, 'raid_id' => 7, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 32527, 'raid_id' => 7, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 32528, 'raid_id' => 7, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 32593, 'raid_id' => 7, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 32606, 'raid_id' => 7, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 32608, 'raid_id' => 7, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 32943, 'raid_id' => 7, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 32944, 'raid_id' => 5, 'boss_id' => 22, 'group' => null],
            ['id' => 33054, 'raid_id' => 4, 'boss_id' => 17, 'group' => null],
            ['id' => 33055, 'raid_id' => 4, 'boss_id' => 16, 'group' => null],
            ['id' => 33058, 'raid_id' => 4, 'boss_id' => 20, 'group' => null],
            ['id' => 33191, 'raid_id' => 8, 'boss_id' => 41, 'group' => null],
            ['id' => 33203, 'raid_id' => 8, 'boss_id' => 41, 'group' => null],
            ['id' => 33206, 'raid_id' => 8, 'boss_id' => 41, 'group' => null],
            ['id' => 33211, 'raid_id' => 8, 'boss_id' => 41, 'group' => null],
            ['id' => 33214, 'raid_id' => 8, 'boss_id' => 40, 'group' => null],
            ['id' => 33215, 'raid_id' => 8, 'boss_id' => 40, 'group' => null],
            ['id' => 33216, 'raid_id' => 8, 'boss_id' => 40, 'group' => null],
            ['id' => 33281, 'raid_id' => 8, 'boss_id' => 40, 'group' => null],
            ['id' => 33283, 'raid_id' => 8, 'boss_id' => 40, 'group' => null],
            ['id' => 33285, 'raid_id' => 8, 'boss_id' => 41, 'group' => null],
            ['id' => 33286, 'raid_id' => 8, 'boss_id' => 40, 'group' => null],
            ['id' => 33293, 'raid_id' => 8, 'boss_id' => 40, 'group' => null],
            ['id' => 33297, 'raid_id' => 8, 'boss_id' => 43, 'group' => null],
            ['id' => 33298, 'raid_id' => 8, 'boss_id' => 44, 'group' => null],
            ['id' => 33299, 'raid_id' => 8, 'boss_id' => 43, 'group' => null],
            ['id' => 33300, 'raid_id' => 8, 'boss_id' => 43, 'group' => null],
            ['id' => 33303, 'raid_id' => 8, 'boss_id' => 43, 'group' => null],
            ['id' => 33317, 'raid_id' => 8, 'boss_id' => 43, 'group' => null],
            ['id' => 33322, 'raid_id' => 8, 'boss_id' => 43, 'group' => null],
            ['id' => 33326, 'raid_id' => 8, 'boss_id' => 42, 'group' => null],
            ['id' => 33327, 'raid_id' => 8, 'boss_id' => 41, 'group' => null],
            ['id' => 33328, 'raid_id' => 8, 'boss_id' => 42, 'group' => null],
            ['id' => 33329, 'raid_id' => 8, 'boss_id' => 42, 'group' => null],
            ['id' => 33332, 'raid_id' => 8, 'boss_id' => 42, 'group' => null],
            ['id' => 33354, 'raid_id' => 8, 'boss_id' => 42, 'group' => null],
            ['id' => 33356, 'raid_id' => 8, 'boss_id' => 42, 'group' => null],
            ['id' => 33357, 'raid_id' => 8, 'boss_id' => 42, 'group' => null],
            ['id' => 33388, 'raid_id' => 8, 'boss_id' => 44, 'group' => null],
            ['id' => 33389, 'raid_id' => 8, 'boss_id' => 44, 'group' => null],
            ['id' => 33421, 'raid_id' => 8, 'boss_id' => 44, 'group' => null],
            ['id' => 33432, 'raid_id' => 8, 'boss_id' => 44, 'group' => null],
            ['id' => 33446, 'raid_id' => 8, 'boss_id' => 44, 'group' => null],
            ['id' => 33453, 'raid_id' => 8, 'boss_id' => 44, 'group' => null],
            ['id' => 33463, 'raid_id' => 8, 'boss_id' => 44, 'group' => null],
            ['id' => 33464, 'raid_id' => 8, 'boss_id' => 44, 'group' => null],
            ['id' => 33465, 'raid_id' => 8, 'boss_id' => 44, 'group' => null],
            ['id' => 33466, 'raid_id' => 8, 'boss_id' => 45, 'group' => null],
            ['id' => 33467, 'raid_id' => 8, 'boss_id' => 45, 'group' => null],
            ['id' => 33468, 'raid_id' => 8, 'boss_id' => 45, 'group' => null],
            ['id' => 33469, 'raid_id' => 8, 'boss_id' => 45, 'group' => null],
            ['id' => 33471, 'raid_id' => 8, 'boss_id' => 45, 'group' => null],
            ['id' => 33473, 'raid_id' => 8, 'boss_id' => 45, 'group' => null],
            ['id' => 33474, 'raid_id' => 8, 'boss_id' => 45, 'group' => null],
            ['id' => 33476, 'raid_id' => 8, 'boss_id' => 45, 'group' => null],
            ['id' => 33478, 'raid_id' => 8, 'boss_id' => 45, 'group' => null],
            ['id' => 33479, 'raid_id' => 8, 'boss_id' => 45, 'group' => null],
            ['id' => 33480, 'raid_id' => 8, 'boss_id' => null, 'group' => 'Timed reward chests'],
            ['id' => 33481, 'raid_id' => 8, 'boss_id' => null, 'group' => 'Timed reward chests'],
            ['id' => 33483, 'raid_id' => 8, 'boss_id' => null, 'group' => 'Timed reward chests'],
            ['id' => 33489, 'raid_id' => 8, 'boss_id' => null, 'group' => 'Timed reward chests'],
            ['id' => 33490, 'raid_id' => 8, 'boss_id' => null, 'group' => 'Timed reward chests'],
            ['id' => 33491, 'raid_id' => 8, 'boss_id' => null, 'group' => 'Timed reward chests'],
            ['id' => 33492, 'raid_id' => 8, 'boss_id' => null, 'group' => 'Timed reward chests'],
            ['id' => 33493, 'raid_id' => 8, 'boss_id' => null, 'group' => 'Timed reward chests'],
            ['id' => 33494, 'raid_id' => 8, 'boss_id' => null, 'group' => 'Timed reward chests'],
            ['id' => 33495, 'raid_id' => 8, 'boss_id' => null, 'group' => 'Timed reward chests'],
            ['id' => 33496, 'raid_id' => 8, 'boss_id' => null, 'group' => 'Timed reward chests'],
            ['id' => 33497, 'raid_id' => 8, 'boss_id' => null, 'group' => 'Timed reward chests'],
            ['id' => 33498, 'raid_id' => 8, 'boss_id' => null, 'group' => 'Timed reward chests'],
            ['id' => 33499, 'raid_id' => 8, 'boss_id' => null, 'group' => 'Timed reward chests'],
            ['id' => 33500, 'raid_id' => 8, 'boss_id' => null, 'group' => 'Timed reward chests'],
            ['id' => 33533, 'raid_id' => 8, 'boss_id' => 43, 'group' => null],
            ['id' => 33590, 'raid_id' => 8, 'boss_id' => null, 'group' => 'Timed reward chests'],
            ['id' => 33591, 'raid_id' => 8, 'boss_id' => null, 'group' => 'Timed reward chests'],
            ['id' => 33592, 'raid_id' => 8, 'boss_id' => 44, 'group' => null],
            ['id' => 33640, 'raid_id' => 8, 'boss_id' => 41, 'group' => null],
            ['id' => 33805, 'raid_id' => 8, 'boss_id' => null, 'group' => 'Timed reward chests'],
            ['id' => 33828, 'raid_id' => 8, 'boss_id' => 44, 'group' => null],
            ['id' => 33829, 'raid_id' => 8, 'boss_id' => 44, 'group' => null],
            ['id' => 33830, 'raid_id' => 8, 'boss_id' => 45, 'group' => null],
            ['id' => 33831, 'raid_id' => 8, 'boss_id' => 45, 'group' => null],
            ['id' => 33971, 'raid_id' => 8, 'boss_id' => null, 'group' => 'Timed reward chests'],
            ['id' => 34011, 'raid_id' => 7, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 34012, 'raid_id' => 7, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 34029, 'raid_id' => 8, 'boss_id' => 44, 'group' => null],
            ['id' => 34164, 'raid_id' => 9, 'boss_id' => 46, 'group' => null],
            ['id' => 34165, 'raid_id' => 9, 'boss_id' => 46, 'group' => null],
            ['id' => 34166, 'raid_id' => 9, 'boss_id' => 46, 'group' => null],
            ['id' => 34167, 'raid_id' => 9, 'boss_id' => 46, 'group' => null],
            ['id' => 34168, 'raid_id' => 9, 'boss_id' => 46, 'group' => null],
            ['id' => 34169, 'raid_id' => 9, 'boss_id' => 46, 'group' => null],
            ['id' => 34170, 'raid_id' => 9, 'boss_id' => 46, 'group' => null],
            ['id' => 34176, 'raid_id' => 9, 'boss_id' => 47, 'group' => null],
            ['id' => 34177, 'raid_id' => 9, 'boss_id' => 47, 'group' => null],
            ['id' => 34178, 'raid_id' => 9, 'boss_id' => 47, 'group' => null],
            ['id' => 34179, 'raid_id' => 9, 'boss_id' => 47, 'group' => null],
            ['id' => 34180, 'raid_id' => 9, 'boss_id' => 47, 'group' => null],
            ['id' => 34181, 'raid_id' => 9, 'boss_id' => 47, 'group' => null],
            ['id' => 34182, 'raid_id' => 9, 'boss_id' => 48, 'group' => null],
            ['id' => 34183, 'raid_id' => 9, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 34184, 'raid_id' => 9, 'boss_id' => 48, 'group' => null],
            ['id' => 34185, 'raid_id' => 9, 'boss_id' => 48, 'group' => null],
            ['id' => 34186, 'raid_id' => 9, 'boss_id' => 48, 'group' => null],
            ['id' => 34188, 'raid_id' => 9, 'boss_id' => 48, 'group' => null],
            ['id' => 34189, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 34190, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 34192, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 34193, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 34194, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 34195, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 34196, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 34197, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 34198, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 34199, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 34202, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 34203, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 34204, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 34205, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 34206, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 34208, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 34209, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 34210, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 34211, 'raid_id' => 9, 'boss_id' => 50, 'group' => null],
            ['id' => 34212, 'raid_id' => 9, 'boss_id' => 50, 'group' => null],
            ['id' => 34213, 'raid_id' => 9, 'boss_id' => 50, 'group' => null],
            ['id' => 34214, 'raid_id' => 9, 'boss_id' => 50, 'group' => null],
            ['id' => 34215, 'raid_id' => 9, 'boss_id' => 50, 'group' => null],
            ['id' => 34216, 'raid_id' => 9, 'boss_id' => 50, 'group' => null],
            ['id' => 34228, 'raid_id' => 9, 'boss_id' => 50, 'group' => null],
            ['id' => 34229, 'raid_id' => 9, 'boss_id' => 50, 'group' => null],
            ['id' => 34230, 'raid_id' => 9, 'boss_id' => 50, 'group' => null],
            ['id' => 34231, 'raid_id' => 9, 'boss_id' => 50, 'group' => null],
            ['id' => 34232, 'raid_id' => 9, 'boss_id' => 50, 'group' => null],
            ['id' => 34233, 'raid_id' => 9, 'boss_id' => 50, 'group' => null],
            ['id' => 34234, 'raid_id' => 9, 'boss_id' => 50, 'group' => null],
            ['id' => 34240, 'raid_id' => 9, 'boss_id' => 50, 'group' => null],
            ['id' => 34241, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34242, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34243, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34244, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34245, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34247, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34329, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34331, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34332, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34333, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34335, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34336, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34337, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34339, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34340, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34341, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34342, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34343, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34344, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34345, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34346, 'raid_id' => 9, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 34347, 'raid_id' => 9, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 34348, 'raid_id' => 9, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 34349, 'raid_id' => 9, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 34350, 'raid_id' => 9, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 34351, 'raid_id' => 9, 'boss_id' => null, 'group' => 'Trash drops'],
            ['id' => 34352, 'raid_id' => 9, 'boss_id' => 48, 'group' => null],
            ['id' => 34403, 'raid_id' => 9, 'boss_id' => 51, 'group' => null],
            ['id' => 34427, 'raid_id' => 9, 'boss_id' => 50, 'group' => 'Naaru Slivers'],
            ['id' => 34428, 'raid_id' => 9, 'boss_id' => 50, 'group' => 'Naaru Slivers'],
            ['id' => 34429, 'raid_id' => 9, 'boss_id' => 50, 'group' => 'Naaru Slivers'],
            ['id' => 34430, 'raid_id' => 9, 'boss_id' => 50, 'group' => 'Naaru Slivers'],
            ['id' => 34848, 'raid_id' => 9, 'boss_id' => 46, 'group' => null],
            ['id' => 34851, 'raid_id' => 9, 'boss_id' => 46, 'group' => null],
            ['id' => 34852, 'raid_id' => 9, 'boss_id' => 46, 'group' => null],
            ['id' => 34853, 'raid_id' => 9, 'boss_id' => 47, 'group' => null],
            ['id' => 34854, 'raid_id' => 9, 'boss_id' => 47, 'group' => null],
            ['id' => 34855, 'raid_id' => 9, 'boss_id' => 47, 'group' => null],
            ['id' => 34856, 'raid_id' => 9, 'boss_id' => 48, 'group' => null],
            ['id' => 34857, 'raid_id' => 9, 'boss_id' => 48, 'group' => null],
            ['id' => 34858, 'raid_id' => 9, 'boss_id' => 48, 'group' => null],
            ['id' => 35282, 'raid_id' => 9, 'boss_id' => 50, 'group' => null],
            ['id' => 35283, 'raid_id' => 9, 'boss_id' => 50, 'group' => null],
            ['id' => 35284, 'raid_id' => 9, 'boss_id' => 50, 'group' => null],
            ['id' => 35290, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 35291, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 35292, 'raid_id' => 9, 'boss_id' => 49, 'group' => null],
            ['id' => 35733, 'raid_id' => 9, 'boss_id' => null, 'group' => 'Trash drops'],
        ];

        foreach ($items as $item) {
            Item::query()->updateOrCreate(
                ['id' => $item['id']],
                [
                    'raid_id' => $item['raid_id'],
                    'boss_id' => $item['boss_id'],
                    'group' => $item['group'],
                ]
            );
        }
    }
}
