<?php

namespace App\Services\Discord\Resources;

use App\Services\Discord\Contracts\Resources\Message as MessageContract;
use App\Services\Discord\Enums\MessageType;
use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Attributes\Validation\BooleanType;
use Spatie\LaravelData\Attributes\Validation\IntegerType;
use Spatie\LaravelData\Attributes\Validation\Min;
use Spatie\LaravelData\Attributes\Validation\Nullable;
use Spatie\LaravelData\Attributes\Validation\StringType;
use Spatie\LaravelData\Data;

class Message extends Data implements MessageContract
{
    public function __construct(
        /** @var string Message ID (snowflake) */
        #[StringType]
        public readonly string $id,

        /** @var string ID of the channel the message was sent in (snowflake) */
        #[StringType]
        public readonly string $channel_id,

        /** @var string ISO8601 timestamp; when this message was sent */
        #[StringType]
        public readonly string $timestamp,

        /** @var bool Whether this was a TTS message */
        #[BooleanType]
        public readonly bool $tts,

        /** @var bool Whether this message mentions everyone */
        #[BooleanType]
        public readonly bool $mention_everyone,

        /** @var array<string> Role IDs specifically mentioned in this message */
        public readonly array $mention_roles,

        /** @var array<Attachment> Any attached files not referenced in embeds or components */
        #[DataCollectionOf(Attachment::class)]
        public readonly array $attachments,

        /** @var array<Embed> Any embedded content */
        #[DataCollectionOf(Embed::class)]
        public readonly array $embeds,

        /** @var bool Whether this message is pinned */
        #[BooleanType]
        public readonly bool $pinned,

        /** @var MessageType Type of message */
        public readonly MessageType $type,

        /** @var User|null Author of the message */
        public readonly ?User $author = null,

        /** @var string|null Contents of the message */
        #[Nullable, StringType]
        public readonly ?string $content = null,

        /** @var string|null ISO8601 timestamp; when this message was edited (null if never) */
        #[Nullable, StringType]
        public readonly ?string $edited_timestamp = null,

        /** @var array<User>|null Users specifically mentioned in the message */
        #[DataCollectionOf(User::class)]
        public readonly ?array $mentions = null,

        /** @var string|null If generated by a webhook, the webhook's ID (snowflake) */
        #[Nullable, StringType]
        public readonly ?string $webhook_id = null,

        /** @var int|null Combined bitfield of MessageFlag values */
        #[Nullable, IntegerType, Min(0)]
        public readonly ?int $flags = null,

        /** @var MessageReference|null Data showing the source of a crosspost, follow add, pin, or reply */
        public readonly ?MessageReference $message_reference = null,

        /** @var Message|null The message associated with the message_reference */
        public readonly ?Message $referenced_message = null,

        /** @var string|null ID of the application if this is an interaction or app-owned webhook (snowflake) */
        #[Nullable, StringType]
        public readonly ?string $application_id = null,

        /** @var int|null Approximate position of the message in a thread */
        #[Nullable, IntegerType, Min(0)]
        public readonly ?int $position = null,

        /** @var int|string|null Used for validating a message was sent */
        public readonly int|string|null $nonce = null,
    ) {}
}
