<?php

namespace App\Services\Discord\Resources;

use App\Services\Discord\Contracts\Resources\Message as MessageContract;
use App\Services\Discord\Enums\MessageType;
use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Attributes\Validation\BooleanType;
use Spatie\LaravelData\Attributes\Validation\IntegerType;
use Spatie\LaravelData\Attributes\Validation\Min;
use Spatie\LaravelData\Attributes\Validation\Nullable;
use Spatie\LaravelData\Attributes\Validation\StringType;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Optional;

class Message extends Data implements MessageContract
{
    public function __construct(
        /** @var string Message ID (snowflake) */
        #[StringType]
        public readonly string $id,

        /** @var string ID of the channel the message was sent in (snowflake) */
        #[StringType]
        public readonly string $channel_id,

        /** @var string ISO8601 timestamp; when this message was sent */
        #[StringType]
        public readonly string $timestamp,

        /** @var bool Whether this was a TTS message */
        #[BooleanType]
        public readonly bool $tts,

        /** @var bool Whether this message mentions everyone */
        #[BooleanType]
        public readonly bool $mention_everyone,

        /** @var array<string> Role IDs specifically mentioned in this message */
        public readonly array $mention_roles,

        /** @var array<Attachment> Any attached files not referenced in embeds or components */
        #[DataCollectionOf(Attachment::class)]
        public readonly array $attachments,

        /** @var array<Embed> Any embedded content */
        #[DataCollectionOf(Embed::class)]
        public readonly array $embeds,

        /** @var bool Whether this message is pinned */
        #[BooleanType]
        public readonly bool $pinned,

        /** @var MessageType Type of message */
        public readonly MessageType $type,

        /** @var User|Optional Author of the message */
        public readonly User|Optional $author,

        /** @var string|Optional Contents of the message */
        #[Nullable, StringType]
        public readonly string|Optional $content,

        /** @var string|Optional ISO8601 timestamp; when this message was edited (null if never) */
        #[Nullable, StringType]
        public readonly string|Optional $edited_timestamp,

        /** @var array<User>|Optional Users specifically mentioned in the message */
        #[DataCollectionOf(User::class)]
        public readonly array|Optional $mentions,

        /** @var string|Optional If generated by a webhook, the webhook's ID (snowflake) */
        #[Nullable, StringType]
        public readonly string|Optional $webhook_id,

        /** @var int|Optional Combined bitfield of MessageFlag values */
        #[Nullable, IntegerType, Min(0)]
        public readonly int|Optional $flags,

        /** @var MessageReference|Optional Data showing the source of a crosspost, follow add, pin, or reply */
        public readonly MessageReference|Optional $message_reference,

        /** @var Message|Optional The message associated with the message_reference */
        public readonly Message|Optional $referenced_message,

        /** @var string|Optional ID of the application if this is an interaction or app-owned webhook (snowflake) */
        #[Nullable, StringType]
        public readonly string|Optional $application_id,

        /** @var int|Optional Approximate position of the message in a thread */
        #[Nullable, IntegerType, Min(0)]
        public readonly int|Optional $position,

        /** @var int|string|Optional Used for validating a message was sent */
        public readonly int|string|Optional $nonce,
    ) {}
}
